### ISSUE TITLE
Dimension should have a timer so you aren't permanently stuck in there

### ISSUE THREAD

**Issue by YaBoiKino** [IllusiveBIair/Naruto-Evolution-Community#35] opened 2021-09-04 05:33 UTC
Dimension should have a timer so you aren't permanently stuck in there

**Comment by douglasparker** [comment] 2021-09-05 04:54
I don't have enough information on this. Are people permanently stuck every time it is used on them? It it only in some cases? Steps to reproduce?

Please follow the template provided for reporting bugs.

**Comment by IllusiveBIair** [comment] 2021-09-09 20:55
Closing this because the issue was resolved.

**Closed by IllusiveBIair** 2021-09-09 20:55 UTC
Labels: Priority: 2-Medium, Type: Feature Request, Review: Approved
