### ISSUE TITLE
Food Pills

### ISSUE THREAD

**Issue by YaBoiKino** [IllusiveBIair/Naruto-Evolution-Community#23] opened 2021-09-03 17:31 UTC
They dont work.

**Comment by IllusiveBIair** [comment] 2021-09-03 17:45
Food pills do function but there's no indicator for them currently. They just increase the rate of your passive regeneration for 20 seconds. They DO NOT bypass regeneration being halted temporarily from taking damage. Feel free to correct me if you find this not to be the case.

**Comment by YaBoiKino** [comment] 2021-09-03 18:30
Ill double check

**Comment by douglasparker** [comment] 2021-09-05 05:01
We need more information on this issue.

**Comment by IllusiveBIair** [comment] 2021-09-11 01:13
I'm closing this issue as I've received no additional info on this not working. As far as I can see they are functioning as intended.

**Closed by IllusiveBIair** 2021-09-11 01:13 UTC
Labels: Type: Bug, Category: Software, Feedback: Need More Information
