### ISSUE TITLE
You can use Warp Rasengan on targets you've marked with your kunai even after it expiring

### ISSUE THREAD

**Issue by Haikuno** [IllusiveBIair/Naruto-Evolution-Community#10] opened 2021-09-02 02:44 UTC
**Steps to Reproduce:**
1. Hit someone with Flying Thunder God : Kunai
2. Wait a couple of minutes
3. Cast Warp Rasengan on the target you've hit before

**Expected Behavior:**
You shouldn't be able to cast Warp Rasengan on targets whose mark has already expired

**Comment by IllusiveBIair** [comment] 2021-09-02 21:52
Thank you I will be investigating this issue.

**Comment by Haikuno** [comment] 2021-09-03 02:48
I've just noticed this also applies to Flying Thunder God, very annoying when trying to teleport away and get teleported in front of the very person you're running away from lol.

**Comment by IllusiveBIair** [comment] 2021-09-03 18:59
I've fixed the issue with warp rasengan although flying thunder god seems to be working fine during testing so I'll need more information on how to reproduce the bug with flying thunder god specifically. However warp rasengan will be fixed in the next hotfix.

**Comment by Haikuno** [comment] 2021-09-03 19:09
Hit a target with a kunai, and leave them targeted. Throw a kunai away from them. Even after the kunai mark expires, you still are able to teleport to them. It should teleport you to your kunai

**Comment by IllusiveBIair** [comment] 2021-09-03 21:36
Issue is resolved and will be coming in the next hotfix.

**Closed** 2021-09-04 23:23 UTC
Labels: Type: Bug, Status: Complete
